name: Android Deploy
run-name: Android Deploy execute by @${{ github.actor }}

on:
  push:
    branches:
      - 'RC**'

env:
  REPO_USERID: ${{ secrets.REPO_USERID }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:
  lint-test-sonar-artifact:
    name: Lint & Test & Sonar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Project
        uses: ./.github/actions/android

      - name: Run Lint
        run: ./gradlew app:lintDebug

      - name: Upload Lint Report
        uses: actions/upload-artifact@v3
        with:
          name: lint_report
          path: app/build/reports/lint-results-debug.html

      - name: Run Jacoco Test Coverage Verification
        run: ./gradlew app:jacocoTestCoverageVerification

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Upload Coverage Test Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco_test_report
          path: app/build/reports/jacoco/jacocoTestReport/

      - name: Run SonarQube Scan
        run: ./gradlew app:sonarqube -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.login=${{ secrets.SONARCLOUDTOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run AssembleStaging
        run: ./gradlew app:assembleStaging --stacktrace
        shell: bash

      - name: Upload Artifact APK
        uses: actions/upload-artifact@v2
        with:
          name: apk-qa
          path: ./app/build/outputs/apk/staging