name: Android Artifact
run-name: Android Artifact execute by @${{ github.actor }}

on: [ workflow_dispatch ]

env:
  REPO_USERID: ${{ secrets.REPO_USERID }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:
  artifact:
    name: Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Project
        uses: ./.github/actions/android

      - name: Run AssembleStaging
        run: ./gradlew app:assembleStaging --stacktrace
        shell: bash

      - name: Upload Artifact APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-qa
          path: ./app/build/outputs/apk/staging