name: Android Deploy

on:
  push:
    branches:
      - 'develop'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      REPO_USERID: ${{ secrets.REPO_USERID }}
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Step
        uses: ./.github/workflows/actions/configure

      - name: Run Lint
        run: ./gradlew app:lintDebug

      - name: Upload Lint Test Report
        uses: actions/upload-artifact@v2
        with:
          name: lint_report
          path: app/build/reports/lint-results-debug.html

  code-analysis:
    name: Code Analysis
    needs: [ lint ]
    runs-on: ubuntu-latest
    env:
      REPO_USERID: ${{ secrets.REPO_USERID }}
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Step
        uses: ./.github/workflows/actions/configure

      - name: Run Lint
        run: ./gradlew app:lintDebug

      - name: Run Tests
        run: ./gradlew app:testDebugUnitTest

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Run Jacoco Test Report
        run: ./gradlew app:jacocoTestReport

      - name: Upload Coverage Test Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco_test_report
          path: app/build/reports/jacoco/jacocoTestReport/

      - name: Run Jacoco Test Coverage Verification
        run: ./gradlew app:jacocoTestCoverageVerification

      - name: Run SonarQube Scan
        run: ./gradlew app:sonarqube -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.login=${{ secrets.SONARCLOUDTOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  artifact:
    name: Artifact
    needs: [ code-analysis ]
    runs-on: ubuntu-latest
    env:
      REPO_USERID: ${{ secrets.REPO_USERID }}
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Step
        uses: ./.github/workflows/actions/configure

      - name: Run AssembleQa
        run: ./gradlew app:assembleQa

      - name: Upload Artifact APK
        uses: actions/upload-artifact@v2
        with:
          name: apk-qa
          path: ./app/build/outputs/apk/qa