name: Android Build QA

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Submodule
        uses: ./.github/workflows/submodule-action

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run lint
        run: ./gradlew app:lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint_report
          path: app/build/reports/lint-results-debug.html

  unit-test:
    name: Unit Test
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Submodule
        uses: ./.github/workflows/submodule-action

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew app:testDebug

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  jacoco:
    name: Coverage Test
    needs: [ unit-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Submodule
        uses: ./.github/workflows/submodule-action

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run Jacoco Test Report
        run: ./gradlew app:jacocoTestReport

      - name: Upload coverage test report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco_test_report
          path: app/build/reports/jacoco/jacocoTestReport/

      - name: Run Jacoco Test Coverage Verification
        run: ./gradlew app:jacocoTestCoverageVerification

  sonarqube:
    name: Analysis Code
    needs: [ jacoco ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Submodule
        uses: ./.github/workflows/submodule-action

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: SonarCloud Scan
        run: ./gradlew app:sonarqube -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.login=${{ secrets.SONARCLOUDTOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  package:
    name: Generate APK
    needs: [ sonarqube ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Submodule
        uses: ./.github/workflows/submodule-action

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: List artifact APK
        run: ls -la

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk-debug
          path: ./app/build/outputs/apk/debug